### ISSUE TITLE
Figure out how to submit HTCondorCluster

### ISSUE THREAD

**Issue by bbockelm** [oshadura/coffea-casa#3]
Customizations needed:
1.  [x] `HTCondorCluster` needs to submit the job to the remote schedd.  This might require a patch to the source.  Assigned: Mat
2.  [x] Select a Docker image to run.  Assigned: Oksana
3.  [x] Add the `xcache_token` to `encrypt_input_files`.  Assigned: Oksana
4.  [x] Setup security object to use the TLS info in `/etc/cmsaf-secrets`.  Assigned: Oksana
5.  [x] For now, hardcode the public IP in the scheduler address.  Assigned: Oksana.
6.  [x] Set `BEARER_TOKEN_FILE` in the worker node environment.  Assigned: Oksana
7.  [x] We're going to have to customize the contact address of the dask worker.  Assigned: Oksana
8.  [x] Publish the port in Docker - https://github.com/clundst/jhub/pull/12
9.  [x] Open port in worker node firewall - see condor submit config in comments below.
10. [x] Set `XCACHE_HOST` to `red-xcache1.unl.edu` on both the worker node and the jupyterlab container.

**Comment by matyasselmeci** [comment]
Relevant issues:
- https://github.com/dask/dask-jobqueue/issues/411
- https://github.com/dask/dask-jobqueue/issues/393

**Comment by bbockelm** [comment]
We might be able to avoid dask/dask-jobqueue#393 because we're going to run in Docker universe.  We can use that to avoid the need of a wrapper script, right?

**Comment by bbockelm** [comment]
After https://github.com/clundst/jhub/pull/12 is merged, a per-user port will be opened for the purpose of a Dask scheduler.  Following https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables, we can parse out the public IP and the randomly-assigned port that is the external version of port 8787 inside the container.

**Comment by bbockelm** [comment]
Also, for reference: https://htcondor.readthedocs.io/en/latest/users-manual/docker-universe-applications.html#docker-and-networking

We'll need to have something like:
```
container_service_names = dask
dask_container_port = 8786
```

This will have HTCondor assign the external port at runtime and report it in the `dask_HostPort` ClassAd attribute.  Getting this port would be something like:

```
$ cat $_CONDOR_JOB_AD | grep HostPort | tr -d '"' | awk '{print $NF;}'
```

Getting external hostname is something like:

```
$ cat $_CONDOR_JOB_AD | grep RemoteHost | tr -d '"' | tr '@' ' ' | awk '{print $NF;}'
```

**Comment by bbockelm** [comment]
Oh!  And we'll need to put the TLS info in as well!  This covers creating the `Security` object:

https://distributed.dask.org/en/latest/tls.html

This will get passed to `HTCondorCluster` - although it's not clear to me whether this generates the right `transfer_input_files` attribute.

The location of the generated CA and usercert is covered in https://github.com/oshadura/coffea-casa/issues/2

**Comment by bbockelm** [comment]
@oshadura - we have everything figured out except SSL!

`Security` object can be constructed on the submit side.  We'll use the `prepare-env.sh` script to override this, however, on the worker node side.  The additional command line arguments appear to be:

```
--tls-ca-file PATH1 --tls-cert PATH2 --tls-key PATH3
```

These three files are in `/etc/cmsaf-secrets` and will need to be specified in `transfer_input_files` and `encrypt_input_files`.

**Comment by bbockelm** [comment]
I think we're all done!
